### PR TITLE
Hotfix: PHP 7.4 compatibility

### PR DESCRIPTION
**Pull request by waahhhh**
**Provide a narrative description of what you are trying to accomplish:**
* Noticed deprecated messages on PHP 7.4:
```text
[10-Dec-2019 04:18:49 UTC] PHP Deprecated:  Function ReflectionType::__toString() is deprecated in /var/www/html/vendor/zendframework/zend-di/src/Definition/Reflection/Parameter.php on line 65
[10-Dec-2019 04:18:49 UTC] PHP Stack trace:
[10-Dec-2019 04:18:49 UTC] PHP   1. {main}() /var/www/html/bin/di-generate-aot.php:0
[10-Dec-2019 04:18:49 UTC] PHP   2. Zend\Di\CodeGenerator\InjectorGenerator->generate() /var/www/html/bin/di-generate-aot.php:22
[10-Dec-2019 04:18:49 UTC] PHP   3. Zend\Di\CodeGenerator\InjectorGenerator->generateTypeFactory() /var/www/html/vendor/zendframework/zend-di/src/CodeGenerator/InjectorGenerator.php:196
[10-Dec-2019 04:18:49 UTC] PHP   4. Zend\Di\CodeGenerator\FactoryGenerator->generate() /var/www/html/vendor/zendframework/zend-di/src/CodeGenerator/InjectorGenerator.php:147
[10-Dec-2019 04:18:49 UTC] PHP   5. Zend\Di\Resolver\DependencyResolver->resolveParameters() /var/www/html/vendor/zendframework/zend-di/src/CodeGenerator/FactoryGenerator.php:176
[10-Dec-2019 04:18:49 UTC] PHP   6. Zend\Di\Definition\Reflection\Parameter->getType() /var/www/html/vendor/zendframework/zend-di/src/Resolver/DependencyResolver.php:285
```

* On PHP 7.4 CodeSniffer outputs the messages:
```text
Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/vendor/squizlabs/php_codesniffer/CodeSniffer.php on line 2028
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/vendor/squizlabs/php_codesniffer/CodeSniffer/File.php on line 1766
```
But that will be resolved by: https://github.com/zendframework/zend-di/pull/47

---

- [x] Are you fixing a bug?
  - [ ] Detail how the bug is invoked currently.
  - [x] Detail the original, incorrect behavior.
  - [x] Detail the new, expected behavior.
  - [x] Base your feature on the `master` branch, and submit against that branch.
  - [ ] Add a regression test that demonstrates the bug, and proves the fix.
  - [ ] Add a `CHANGELOG.md` entry for the fix.

- [ ] Are you creating a new feature?
  - [ ] Why is the new feature needed? What purpose does it serve?
  - [ ] How will users use the new feature?
  - [ ] Base your feature on the `develop` branch, and submit against that branch.
  - [ ] Add only one feature per pull request; split multiple features over multiple pull requests
  - [ ] Add tests for the new feature.
  - [ ] Add documentation for the new feature.
  - [ ] Add a `CHANGELOG.md` entry for the new feature.

- [x] Is this related to quality assurance?
* using error reporting on E_ALL for tests to 

- [ ] Is this related to documentation?

### CODE REVIEW

**Comment by michalbundyra** [comment]
@waahhhh Thanks for your contribution.

We can't accept this PR as it is - it contains BC Break (bump PHP version, by us considered as BC Break and can be released only with new major version) and Bugfix for PHP 7.4 compatibility.

Please provide bugfix separately - PR to master, and then other PR with bumped PHP version to develop. Thanks!

**Comment by waahhhh** [comment]
Removed version dump and changed `phpunit/phpunit` version from 8.5 to 7.5.

**Comment by michalbundyra** [comment]
Thanks, @waahhhh!

**Comment by tux-rampage** [comment]
This PR does not pass static analysis. Why didn't this PR trigger a travis build?

**Comment by michalbundyra** [comment]
@tux-rampage PR was to master, was merged as a hotfix.

**Comment by tux-rampage** [comment]
I see, thanks

**Pull request merged**
